# GBP/USD Feature Engineering

In [9]:
import pandas as pd
import numpy as np

## Load Data

In [3]:
# Load dtype map
dtype_map = pd.read_csv("../data/cleaned/gbpusd/v1_11-09-25/gbpusd_cleaned_dtypes_as_of_110925.csv").to_dict()

# Convert dtype strings to actual Python types
dtype_map = {
    col: eval(dtype_str) if "float" in dtype_str or "int" in dtype_str else "object"
    for col, dtype_str in dtype_map.items()
}

# Load cleaned data with correct types
gbpusd_cleaned = pd.read_csv("../data/cleaned/gbpusd/v1_11-09-25/gbpusd_cleaned_as_of_110925.csv", dtype=dtype_map, parse_dates=[0], index_col=0)

In [4]:
gbpusd_cleaned.head()

            gbp_usd_noon_rate
date
1971-01-04             2.3938
1971-01-05             2.3949
1971-01-06             2.3967
1971-01-07             2.3963
1971-01-08             2.3972

## GBP/USD Features

In [5]:
gbpused_features = gbpusd_cleaned.copy()

### Returns

In [7]:
gbpused_features["simple_return"] = gbpused_features["gbp_usd_noon_rate"].pct_change(fill_method=None)

In [10]:
gbpused_features["log_return"] = np.log(gbpused_features["simple_return"] + 1)

In [11]:
gbpused_features.head()

            gbp_usd_noon_rate  simple_return  log_return
date
1971-01-04             2.3938            NaN         NaN
1971-01-05             2.3949       0.000460    0.000459
1971-01-06             2.3967       0.000752    0.000751
1971-01-07             2.3963      -0.000167   -0.000167
1971-01-08             2.3972       0.000376    0.000376

## Export

In [12]:
gbpused_features.to_csv("../data/features/gbpusd/v1_11-09-25/gbpusd_features_as_of_110925.csv")
gbpused_features.dtypes.to_csv("../data/features/gbpusd/v1_11-09-25/gbpusd_features_dtypes_as_of_110925.csv")